FROM python:3.11

# let's copy all the necessary files
# we install our only 2 dependencies :) and vim for nice workflow
RUN apt-get update && \
    apt-get install -y vim
RUN python3 -m pip install --upgrade pip
WORKDIR /scratch
COPY . .
RUN python3 -m pip install .
WORKDIR /app
RUN video_sampler --help
