# Whether to process only keyframes (it's way faster than processing all frames)
# Read interval while processing video (in seconds) (when there's no frame yielded, when to check again)
queue_wait: 0.1
debug: false
# Whether to print stats
print_stats: false
# Buffer configuration
buffer_config:
  type: grid
  # the smaller the hash size, the greater chance of collision
  # smaller hashsets are faster to process & reduce frames more aggressively
  hash_size: 8
  # size of the collision buffer. The larger the buffer, the more in time back the
  # hashes are stored.
  grid_x: 5
  grid_y: 5
  max_hits: 2
  size: 15
  debug: false
# Gating configuration
gate_config:
  type: pass
extractor_config: {}
summary_config: {}
# Number of workers (separate processes) to process the frames. Determines level of parallelism
n_workers: 3
save_format:
  encode_time_b64: false
  include_filename: false
  avoid_dot: false

frame_time_regex: '(\d+(?:\.\d+)?)'
